version: "3.3"
services:
  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    links:
      - httpbin
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - 4040:4040
  httpbin:
    container_name: httpbin
    image: kennethreitz/httpbin
    ports:
      - "8000:80"
